name: Get Android SHA

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Get SHA fingerprints
        run: |
          cd android
          chmod +x gradlew
          ./gradlew signingReport
